@startuml

!include https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4_Container.puml

!define DEVICONS https://raw.githubusercontent.com/tupadr3/plantuml-icon-font-sprites/master/devicons
!define DEVICONS2 https://raw.githubusercontent.com/tupadr3/plantuml-icon-font-sprites/master/devicons2

!include DEVICONS/database.puml
!include DEVICONS2/angularjs.puml
!include DEVICONS2/csharp.puml
!include DEVICONS2/postgresql.puml

Person(User, "User")

System_Ext(BankingSystem, "Banking System", "Provides money transations")
System_Ext(PartnerSystem, "Partner's System", "System of a partner like shop, tour operator and etc.")
System_Ext(EmailSystem, "E-mail System", "Any e-mail system")
System_Ext(HotelSystem, "Hotel System", "A hotel that one of the hotel accounts represent")

System_Boundary(Hb_container, "Hotel Booking") {
	Container(Spa, "Single-Page Applicaiton", "TypeScript and Angular", "Provides all functionality for hotel booking via web-browser", $sprite="angularjs")

	'Container(Api, "API Application", "C# and ASP.NET Core", "Provides all functionality for hotel booking via a JSON/HTTPS API", $sprite="csharp")

	Container(Booking, "Booking Service", "C# and ASP.NET Core", "Provides all functionality for hotel booking via a JSON/HTTPS API", $sprite="csharp")

	Container(PartnerService, "Partner Service", "C# and ASP.NET Core", "Communicates partner data, special offers and etc. via a JSON/HTTPS API", $sprite="csharp")

	Container(Web, "Web Application", "C# and ASP.NET Core", "Delivers static content and hotel booking single-page application", $sprite="csharp")

	Container(Auth, "Auth Service", "C# and ASP.NET Core", "Responsible for operations with user accounts like authentication, registration, user roles and etc.", $sprite="csharp")

	Container(Reviews, "Reviews Service", "C# and ASP.NET Core", "Responsible for managing reviews", $sprite="csharp")

	ContainerDb(HotelBookingDb, "Database", "PostgreSQL", "Stores user, reservations, reviews and other information", $sprite="postgresql")

	Container(Analytics, "Analytics API Application", "C# and ASP.NET Core", "Gathers information of user's actions and analyses it", $sprite="csharp")

	ContainerDb(AnalyticsDb, "Analytics Database", "ClickHouse", "Database for analytical processing", $sprite="database")

	'TODO: Add analytics application, hotel connector application

	Rel_R(Web, Spa, "Delivers content to the customer's web browser")
	Rel(Spa, Booking, "Makes API calls to", "JSON/HTTPS")
	Rel_L(Spa, Auth, "Sends information about user to and gets it from", "JSON/HTTPS")
	Rel_L(Booking, PartnerService, "Makes API calls to", "JSON/HTTPS")
	Rel_D(Spa, Reviews, "Makes API calls to", "JSON/HTTPS")
	Rel_D(Spa, PartnerService, "Makes API calls to", "JSON/HTTPS")

	Rel_D(Booking, HotelBookingDb, "Reads from and writes to", "SQL/TCP")
	Rel_D(Auth, HotelBookingDb, "Reads from and writes to", "SQL/TCP")
	Rel_D(Reviews, HotelBookingDb, "Reads from and writes to", "SQL/TCP")
	Rel_D(PartnerService, HotelBookingDb, "Reads from and writes to", "SQL/TCP")

	Rel_D(Analytics, AnalyticsDb, "Reads from and writes to", "SQL/TCP")
	Rel_D(Booking, Analytics, "Sends data for analysis to", "HTTPS")

	Rel_D(User, Web, "Visits site using", "HTTPS")
	Rel_D(User, Spa, "Views hotels, manages reservations, reviews and etc.")

	Rel_D(Booking, EmailSystem, "Sends e-mails using", "HTTPS")
	Rel_D(Booking, BankingSystem, "Makes payments using", "HTTPS")
	Rel_D(PartnerService, PartnerSystem, "Gets information about special offers and promotions from", "https")
	Rel_D(Booking, HotelSystem, "Sends information about guests' reservations to, and gets data about free rooms, prices and promotions from", "https")
}

Rel_U(User, EmailSystem, "Reads e-mails from", "HTTPS")

@enduml