@startuml

'Items
[User browser]
[User mobile app]

[Api gateway]
[Load Balancer]

[User browser] --> [Api gateway]
[User mobile app] --> [Api gateway]
[Api gateway] --> [Load Balancer]

package "Kubernetes Cluster" {
    node "k8s node" {
        [Web app and SPA POD]
        [API application POD]
        [Account service POD]
        [Admin service POD]
        [Reviews service POD]
        [Partner service POD]
        [Booking service POD]
        [Analytics API application POD]
    }
}

package "External Services" {
    database "DB"
    database "Analytics DB"
    [Message Queue]
}

cloud "External Systems" {
    [Email System]
    [Partner System]
    [Banking System]
    [Hotel System]
}

[Load Balancer] --> [k8s node]
[k8s node] --> [External Services]
[k8s node] --> [External Systems]

@enduml
